/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRegistrationRouteImport } from './routes/vendor-registration'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationStatusRouteImport } from './routes/application-status'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesVendorManagementRouteImport } from './routes/services.vendor-management'
import { Route as ServicesSafetyRouteImport } from './routes/services.safety'
import { Route as ServicesRecruitmentRouteImport } from './routes/services.recruitment'
import { Route as ServicesProcurementRouteImport } from './routes/services.procurement'
import { Route as ServicesOffshoreRouteImport } from './routes/services.offshore'
import { Route as ServicesLogisticsRouteImport } from './routes/services.logistics'
import { Route as ServicesEquipmentRouteImport } from './routes/services.equipment'
import { Route as ServicesDieselRouteImport } from './routes/services.diesel'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as AdminAdminVendorsRouteImport } from './routes/_admin.admin.vendors'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin.admin.reports'
import { Route as AdminAdminQuotesRouteImport } from './routes/_admin.admin.quotes'
import { Route as AdminAdminProductsRouteImport } from './routes/_admin.admin.products'
import { Route as AdminAdminProcurementRouteImport } from './routes/_admin.admin.procurement'
import { Route as AdminAdminJobsRouteImport } from './routes/_admin.admin.jobs'
import { Route as AdminAdminContactsRouteImport } from './routes/_admin.admin.contacts'
import { Route as AdminAdminBlogRouteImport } from './routes/_admin.admin.blog'
import { Route as AdminAdminProcurementIdRouteImport } from './routes/_admin.admin.procurement.$id'

const VendorRegistrationRoute = VendorRegistrationRouteImport.update({
  id: '/vendor-registration',
  path: '/vendor-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationStatusRoute = ApplicationStatusRouteImport.update({
  id: '/application-status',
  path: '/application-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVendorManagementRoute =
  ServicesVendorManagementRouteImport.update({
    id: '/vendor-management',
    path: '/vendor-management',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSafetyRoute = ServicesSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRecruitmentRoute = ServicesRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesProcurementRoute = ServicesProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesOffshoreRoute = ServicesOffshoreRouteImport.update({
  id: '/offshore',
  path: '/offshore',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLogisticsRoute = ServicesLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEquipmentRoute = ServicesEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDieselRoute = ServicesDieselRouteImport.update({
  id: '/diesel',
  path: '/diesel',
  getParentRoute: () => ServicesRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminVendorsRoute = AdminAdminVendorsRouteImport.update({
  id: '/admin/vendors',
  path: '/admin/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminQuotesRoute = AdminAdminQuotesRouteImport.update({
  id: '/admin/quotes',
  path: '/admin/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProductsRoute = AdminAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProcurementRoute = AdminAdminProcurementRouteImport.update({
  id: '/admin/procurement',
  path: '/admin/procurement',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminJobsRoute = AdminAdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminContactsRoute = AdminAdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBlogRoute = AdminAdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProcurementIdRoute = AdminAdminProcurementIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminProcurementRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/application-status': typeof ApplicationStatusRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vendor-registration': typeof VendorRegistrationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/diesel': typeof ServicesDieselRoute
  '/services/equipment': typeof ServicesEquipmentRoute
  '/services/logistics': typeof ServicesLogisticsRoute
  '/services/offshore': typeof ServicesOffshoreRoute
  '/services/procurement': typeof ServicesProcurementRoute
  '/services/recruitment': typeof ServicesRecruitmentRoute
  '/services/safety': typeof ServicesSafetyRoute
  '/services/vendor-management': typeof ServicesVendorManagementRoute
  '/admin/blog': typeof AdminAdminBlogRoute
  '/admin/contacts': typeof AdminAdminContactsRoute
  '/admin/jobs': typeof AdminAdminJobsRoute
  '/admin/procurement': typeof AdminAdminProcurementRouteWithChildren
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/quotes': typeof AdminAdminQuotesRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/vendors': typeof AdminAdminVendorsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/procurement/$id': typeof AdminAdminProcurementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/application-status': typeof ApplicationStatusRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vendor-registration': typeof VendorRegistrationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/diesel': typeof ServicesDieselRoute
  '/services/equipment': typeof ServicesEquipmentRoute
  '/services/logistics': typeof ServicesLogisticsRoute
  '/services/offshore': typeof ServicesOffshoreRoute
  '/services/procurement': typeof ServicesProcurementRoute
  '/services/recruitment': typeof ServicesRecruitmentRoute
  '/services/safety': typeof ServicesSafetyRoute
  '/services/vendor-management': typeof ServicesVendorManagementRoute
  '/admin/blog': typeof AdminAdminBlogRoute
  '/admin/contacts': typeof AdminAdminContactsRoute
  '/admin/jobs': typeof AdminAdminJobsRoute
  '/admin/procurement': typeof AdminAdminProcurementRouteWithChildren
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/quotes': typeof AdminAdminQuotesRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/vendors': typeof AdminAdminVendorsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/procurement/$id': typeof AdminAdminProcurementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/application-status': typeof ApplicationStatusRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vendor-registration': typeof VendorRegistrationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/diesel': typeof ServicesDieselRoute
  '/services/equipment': typeof ServicesEquipmentRoute
  '/services/logistics': typeof ServicesLogisticsRoute
  '/services/offshore': typeof ServicesOffshoreRoute
  '/services/procurement': typeof ServicesProcurementRoute
  '/services/recruitment': typeof ServicesRecruitmentRoute
  '/services/safety': typeof ServicesSafetyRoute
  '/services/vendor-management': typeof ServicesVendorManagementRoute
  '/_admin/admin/blog': typeof AdminAdminBlogRoute
  '/_admin/admin/contacts': typeof AdminAdminContactsRoute
  '/_admin/admin/jobs': typeof AdminAdminJobsRoute
  '/_admin/admin/procurement': typeof AdminAdminProcurementRouteWithChildren
  '/_admin/admin/products': typeof AdminAdminProductsRoute
  '/_admin/admin/quotes': typeof AdminAdminQuotesRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_admin/admin/vendors': typeof AdminAdminVendorsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/procurement/$id': typeof AdminAdminProcurementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/application-status'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faqs'
    | '/industries'
    | '/privacy'
    | '/procurement'
    | '/products'
    | '/projects'
    | '/quote'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/vendor-registration'
    | '/blog/$slug'
    | '/products/$slug'
    | '/services/diesel'
    | '/services/equipment'
    | '/services/logistics'
    | '/services/offshore'
    | '/services/procurement'
    | '/services/recruitment'
    | '/services/safety'
    | '/services/vendor-management'
    | '/admin/blog'
    | '/admin/contacts'
    | '/admin/jobs'
    | '/admin/procurement'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/vendors'
    | '/admin/'
    | '/admin/procurement/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/application-status'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faqs'
    | '/industries'
    | '/privacy'
    | '/procurement'
    | '/products'
    | '/projects'
    | '/quote'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/vendor-registration'
    | '/blog/$slug'
    | '/products/$slug'
    | '/services/diesel'
    | '/services/equipment'
    | '/services/logistics'
    | '/services/offshore'
    | '/services/procurement'
    | '/services/recruitment'
    | '/services/safety'
    | '/services/vendor-management'
    | '/admin/blog'
    | '/admin/contacts'
    | '/admin/jobs'
    | '/admin/procurement'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/vendors'
    | '/admin'
    | '/admin/procurement/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/application-status'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faqs'
    | '/industries'
    | '/privacy'
    | '/procurement'
    | '/products'
    | '/projects'
    | '/quote'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/vendor-registration'
    | '/blog/$slug'
    | '/products/$slug'
    | '/services/diesel'
    | '/services/equipment'
    | '/services/logistics'
    | '/services/offshore'
    | '/services/procurement'
    | '/services/recruitment'
    | '/services/safety'
    | '/services/vendor-management'
    | '/_admin/admin/blog'
    | '/_admin/admin/contacts'
    | '/_admin/admin/jobs'
    | '/_admin/admin/procurement'
    | '/_admin/admin/products'
    | '/_admin/admin/quotes'
    | '/_admin/admin/reports'
    | '/_admin/admin/users'
    | '/_admin/admin/vendors'
    | '/_admin/admin/'
    | '/_admin/admin/procurement/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApplicationStatusRoute: typeof ApplicationStatusRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  IndustriesRoute: typeof IndustriesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcurementRoute: typeof ProcurementRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  QuoteRoute: typeof QuoteRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VendorRegistrationRoute: typeof VendorRegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor-registration': {
      id: '/vendor-registration'
      path: '/vendor-registration'
      fullPath: '/vendor-registration'
      preLoaderRoute: typeof VendorRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-status': {
      id: '/application-status'
      path: '/application-status'
      fullPath: '/application-status'
      preLoaderRoute: typeof ApplicationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/vendor-management': {
      id: '/services/vendor-management'
      path: '/vendor-management'
      fullPath: '/services/vendor-management'
      preLoaderRoute: typeof ServicesVendorManagementRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/safety': {
      id: '/services/safety'
      path: '/safety'
      fullPath: '/services/safety'
      preLoaderRoute: typeof ServicesSafetyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/recruitment': {
      id: '/services/recruitment'
      path: '/recruitment'
      fullPath: '/services/recruitment'
      preLoaderRoute: typeof ServicesRecruitmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/procurement': {
      id: '/services/procurement'
      path: '/procurement'
      fullPath: '/services/procurement'
      preLoaderRoute: typeof ServicesProcurementRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/offshore': {
      id: '/services/offshore'
      path: '/offshore'
      fullPath: '/services/offshore'
      preLoaderRoute: typeof ServicesOffshoreRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/logistics': {
      id: '/services/logistics'
      path: '/logistics'
      fullPath: '/services/logistics'
      preLoaderRoute: typeof ServicesLogisticsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/equipment': {
      id: '/services/equipment'
      path: '/equipment'
      fullPath: '/services/equipment'
      preLoaderRoute: typeof ServicesEquipmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/diesel': {
      id: '/services/diesel'
      path: '/diesel'
      fullPath: '/services/diesel'
      preLoaderRoute: typeof ServicesDieselRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/vendors': {
      id: '/_admin/admin/vendors'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminAdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/quotes': {
      id: '/_admin/admin/quotes'
      path: '/admin/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminAdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/products': {
      id: '/_admin/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/procurement': {
      id: '/_admin/admin/procurement'
      path: '/admin/procurement'
      fullPath: '/admin/procurement'
      preLoaderRoute: typeof AdminAdminProcurementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/jobs': {
      id: '/_admin/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminAdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/contacts': {
      id: '/_admin/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminAdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/blog': {
      id: '/_admin/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminAdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/procurement/$id': {
      id: '/_admin/admin/procurement/$id'
      path: '/$id'
      fullPath: '/admin/procurement/$id'
      preLoaderRoute: typeof AdminAdminProcurementIdRouteImport
      parentRoute: typeof AdminAdminProcurementRoute
    }
  }
}

interface AdminAdminProcurementRouteChildren {
  AdminAdminProcurementIdRoute: typeof AdminAdminProcurementIdRoute
}

const AdminAdminProcurementRouteChildren: AdminAdminProcurementRouteChildren = {
  AdminAdminProcurementIdRoute: AdminAdminProcurementIdRoute,
}

const AdminAdminProcurementRouteWithChildren =
  AdminAdminProcurementRoute._addFileChildren(
    AdminAdminProcurementRouteChildren,
  )

interface AdminRouteChildren {
  AdminAdminBlogRoute: typeof AdminAdminBlogRoute
  AdminAdminContactsRoute: typeof AdminAdminContactsRoute
  AdminAdminJobsRoute: typeof AdminAdminJobsRoute
  AdminAdminProcurementRoute: typeof AdminAdminProcurementRouteWithChildren
  AdminAdminProductsRoute: typeof AdminAdminProductsRoute
  AdminAdminQuotesRoute: typeof AdminAdminQuotesRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminVendorsRoute: typeof AdminAdminVendorsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminBlogRoute: AdminAdminBlogRoute,
  AdminAdminContactsRoute: AdminAdminContactsRoute,
  AdminAdminJobsRoute: AdminAdminJobsRoute,
  AdminAdminProcurementRoute: AdminAdminProcurementRouteWithChildren,
  AdminAdminProductsRoute: AdminAdminProductsRoute,
  AdminAdminQuotesRoute: AdminAdminQuotesRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminVendorsRoute: AdminAdminVendorsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesDieselRoute: typeof ServicesDieselRoute
  ServicesEquipmentRoute: typeof ServicesEquipmentRoute
  ServicesLogisticsRoute: typeof ServicesLogisticsRoute
  ServicesOffshoreRoute: typeof ServicesOffshoreRoute
  ServicesProcurementRoute: typeof ServicesProcurementRoute
  ServicesRecruitmentRoute: typeof ServicesRecruitmentRoute
  ServicesSafetyRoute: typeof ServicesSafetyRoute
  ServicesVendorManagementRoute: typeof ServicesVendorManagementRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesDieselRoute: ServicesDieselRoute,
  ServicesEquipmentRoute: ServicesEquipmentRoute,
  ServicesLogisticsRoute: ServicesLogisticsRoute,
  ServicesOffshoreRoute: ServicesOffshoreRoute,
  ServicesProcurementRoute: ServicesProcurementRoute,
  ServicesRecruitmentRoute: ServicesRecruitmentRoute,
  ServicesSafetyRoute: ServicesSafetyRoute,
  ServicesVendorManagementRoute: ServicesVendorManagementRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  ApplicationStatusRoute: ApplicationStatusRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  IndustriesRoute: IndustriesRoute,
  PrivacyRoute: PrivacyRoute,
  ProcurementRoute: ProcurementRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  QuoteRoute: QuoteRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VendorRegistrationRoute: VendorRegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
